name: buzz
description: Buzz ToDo & Reminders.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  animations: ^2.0.3
  cached_network_image: ^3.2.1
  gap: ^2.0.0
  isar: ^3.0.0-dev.7
  isar_flutter_libs: ^3.0.0-dev.7
  path_provider: ^2.0.11
  shared_preferences: ^2.0.15
  flutter_riverpod: ^1.0.4
  shared_preferences_riverpod: ^0.2.0
  image_picker: ^0.8.5+3
  flutter_local_notifications: ^9.7.0
  uuid: ^3.0.6
  awesome_notifications: ^0.7.0-beta.5
  intl: ^0.17.0


dev_dependencies:
  build_runner: any
  flutter_lints: ^2.0.0
  isar_generator: ^3.0.0-dev.7
  lint: ^1.8.2

flutter:

  uses-material-design: true
